__all__ = [
    'DEFAULT_CONNECTION_TIMEOUT',
    'DEFAULT_READ_TIMEOUT',
    'MagicNumber',
]
import typing as _t

DEFAULT_CONNECTION_TIMEOUT = 5.05
DEFAULT_READ_TIMEOUT = 27.67

class MagicNumber(_t.NamedTuple):
    DEFAULT_CONNECTION_TIMEOUT: float = DEFAULT_CONNECTION_TIMEOUT
    DEFAULT_READ_TIMEOUT: float = DEFAULT_READ_TIMEOUT
