#!/bin/sh
# mv $PROJECT_DIR/scripts/pre_commit .git/hooks/pre-commit
# chmod a+x .git/hooks/pre-commit

CHANGED_PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep ".py\$")

if [ -z "$CHANGED_PYTHON_FILES" ]
then
    echo "No Python files found. No reason to run checks."
    exit 0
fi

set -e

echo "list of new/changed/deleted files: $CHANGED_PYTHON_FILES"

$VENV/bin/flake8 \
    --max-line-length=119 \
    --ignore=E402,F841,F401,E302,E305 \
    --max-complexity=10 \
    $CHANGED_PYTHON_FILES
$VENV/bin/mypy \
    --show-error-codes \
    $CHANGED_PYTHON_FILES

echo "All checks successfully passed."
